# Generated by Django 3.1 on 2020-09-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
