# Generated by Django 3.1 on 2020-09-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
