# Generated by Django 3.1 on 2020-10-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20200927_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(default=12, upload_to='pictures'),
            preserve_default=False,
        ),
    ]
