# Generated by Django 3.1 on 2020-10-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Age',
            new_name='age',
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='pictures'),
        ),
    ]
