# Generated by Django 3.1 on 2020-10-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20201004_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(height_field=200, upload_to='pictures', width_field=200),
        ),
    ]
