# Generated by Django 3.1 on 2020-10-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20201004_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='/media/pictures/default.jpg', null=True, upload_to='pictures'),
        ),
    ]
