# Generated by Django 3.1 on 2020-10-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='/pictures/default.jpg', null=True, upload_to='pictures'),
        ),
    ]
