# Generated by Django 3.1 on 2020-10-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20201011_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upvotedposts',
            field=models.ManyToManyField(related_name='postupvotes', to='project.Post'),
        ),
    ]
