# Generated by Django 3.1 on 2020-10-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_user_upvotedposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pagesfollowed',
            field=models.ManyToManyField(blank=True, related_name='Userpages', to='project.Page'),
        ),
        migrations.AlterField(
            model_name='user',
            name='upvotedposts',
            field=models.ManyToManyField(blank=True, related_name='postupvotes', to='project.Post'),
        ),
    ]
