# Generated by Django 3.1 on 2020-08-29 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userfollows',
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 29, 5, 5, 51, 916434)),
        ),
    ]
