# Generated by Django 3.1 on 2020-08-29 12:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_auto_20200829_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 29, 5, 9, 41, 745930)),
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followeduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followeduser', to=settings.AUTH_USER_MODEL)),
                ('followinguser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followinguser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
