# Generated by Django 3.1 on 2020-08-29 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0024_auto_20200829_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 29, 9, 3, 33, 82297)),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
