# Generated by Django 3.1 on 2020-08-30 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0026_auto_20200830_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 3, 57, 46, 551995)),
        ),
    ]
