# Generated by Django 3.1.6 on 2021-02-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('date', models.DateField(auto_now_add=True)),
                ('paragraph1', models.TextField(blank=True, null=True)),
                ('paragraph2', models.TextField(blank=True, null=True)),
                ('paragraph3', models.TextField(blank=True, null=True)),
                ('paragraph4', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images')),
                ('thumbnail', models.ImageField(upload_to='images')),
            ],
        ),
    ]
