# Generated by Django 3.1.6 on 2021-02-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='qweqwe', max_length=120),
            preserve_default=False,
        ),
    ]
