# Generated by Django 3.1.6 on 2021-02-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210224_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='homepage',
            field=models.BooleanField(default=False),
        ),
    ]
