# Generated by Django 3.1 on 2020-12-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='site-iso',
            new_name='iso',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='site-region',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='site-state',
            new_name='state',
        ),
    ]
